import statemachine
import smart_proj.Sensors


class App(statemachine.StateMachine):

    # Provide a list of sensor types that are needed by the application to operate properly.
    def dependencies_sensors(self) -> []:
        pass

    # Provide a list of actuator types that are needed by the application to operate properly.
    def dependencies_actuators(self) -> []:
        pass

    # Listen to events generated by sensors (observables) and make the neccessary changes to the
    # internal state machine of the app.
    def update(self, subject: smart_proj.Sensors.Sensor) -> None:
        pass
