import statemachine
import smart_proj.Sensors


class App(statemachine.StateMachine):
    typology = None
    name = None

    # Provide a list of sensor types that are needed by the application to operate properly.
    def dependencies_sensors(self) -> []:
        pass

    # Provide a list of actuator types that are needed by the application to operate properly.
    def dependencies_actuators(self) -> []:
        pass

    # Specify the typology of the app
    def set_typology(self, typology: str):
        self.typology = typology

    # Specify the name of the app
    def set_name(self, name : str):
        self.name = name

    # Listen to events generated by sensors (observables) and make the neccessary changes to the
    # internal state machine of the app.
    def update(self, subject: smart_proj.Sensors.Sensor) -> None:
        pass
